PUT http://localhost:3010/api/updateContentById/666e39b4b5ec681251d569d1
Content-Type: application/json
Authorization: bearer 

{
  "title": "Eco-Tourism",
  "description": "Ecotourism is based on extractive tourism, adventure tourism, nature retreats, and wildlife tourism, etc. which combine education, recreation, and adventure. Eco-tourism has evolved quite a bit as a concept. Earlier, the scenic beauty of pristine natural areas would attract many tourists.",
  "links": [
    "https://example.com/course-link",
    "https://example.com/resource-link"
  ],
  "likes": [],
  "keywords": ["Finance and accounts management", "Hiring and training skilled staff"],
  "contentCreatorEmail": "Ramesh@gmail.com",
  "images": [
    "https://example.com/image1.jpg",
    "https://example.com/image2.jpg"
  ]
}