PUT http://localhost:3010/api/updateCourseById/666e0ce31f4b65d4d6ed0037
Content-Type: application/json
Authorization: bearer 

{
  "title": "Introduction to Machine Learning",
  "description": "A beginner-friendly course on machine learning.",
  "links": [
    "https://example.com/course-link",
    "https://example.com/resource-link"
  ],
  "keywords": [
    "Machine Learning",
    "AI",
    "Data Science"
  ],
  "courseCreaterEmail": "creator@example.com",
  "difficulty": "Beginner"
}