POST http://localhost:3010/api/insertUser
Content-Type: application/json

{
    "email": "sureshrr@gmail.com",
    "name": "Suresh S",
    "password": "secure1234",
    "role": 2,
    "keywords": ["Mushroom Farming", "Onion Farming"]
}
