PUT http://localhost:3010/api/updateJobById/666e12e4c86a5316d33ddc1b
Content-Type: application/json

{
  "title": "Updated Software Engineer",
  "description": "An updated description for a software engineer job position.",
  "links": [
    "https://example.com/updated-job-link",
    "https://example.com/updated-resource-link"
  ],
  "keywords": [
    "Updated Engineering",
    "Updated Software",
    "Updated Programming"
  ],
  "recruiterEmail": "updated.recruiter@example.com"
}
