POST http://localhost:3010/api/insertCourse
Content-Type: application/json
Authorization: bearer 

{
  "title": "Goat Farming",
  "description": "Goat farming involves raising and breeding goats for milk, meat, fiber, and skins. Goats are versatile animals that adapt well to various environments and are relatively easy to manage. Goat farming can be a profitable venture and contributes to the livelihoods of many small-scale farmers.",
  "links": [
    "https://example.com/goat-farming-course-link",
    "https://example.com/goat-farming-resource-link"
  ],
  "keywords": [
    "Goat Farming",
    "Livestock",
    "Agriculture"
  ],
  "courseCreaterEmail": "deepa@gmail.com",
  "difficulty": "Beginner"
}
